# Generated by Django 2.2.4 on 2019-08-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_feelings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feelings',
        ),
    ]
